-- 고객 릴레이션
CREATE TABLE CUSTOMER ( 
    CUSTOMER_ID VARCHAR(20) NOT NULL, 
    CUSTOMER_NAME VARCHAR(20) NOT NULL, 
    AGE INT, 
    PRIMARY KEY(CUSTOMER_ID) 
);

INSERT INTO CUSTOMER VALUES ('apple', '김현준', 20);
INSERT INTO CUSTOMER VALUES ('banana', '정소화', 25);
INSERT INTO CUSTOMER VALUES ('carrot', '원유선', 28);
INSERT INTO CUSTOMER VALUES ('orange', '정지영', 22);

-- 주문 릴레이션
CREATE TABLE ORDER_DEMAND ( 
    ORDER_NO CHAR(4) NOT NULL, 
    CUSTOMER_ID VARCHAR(20), 
    PRODUCT_NAME VARCHAR(20), 
    PRIMARY KEY(ORDER_NO)/*, 
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)*/
);

INSERT INTO ORDER_DEMAND VALUES ('1001', 'apple', '진짜우동');
INSERT INTO ORDER_DEMAND VALUES ('1002', 'carrot', '맛있는파이');
INSERT INTO ORDER_DEMAND VALUES ('1003', 'banana', '그대로만두');

-- JOIN
/*SELECT A.CUSTOMER_ID, A.CUSTOMER_NAME, A.AGE
     , B.ORDER_NO, B.CUSTOMER_ID, B.PRODUCT_NAME
*/
SELECT A.*, B.*
-- FROM CUSTOMER AS A, ORDER_DEMAND AS B
FROM CUSTOMER A, ORDER_DEMAND B
WHERE A.CUSTOMER_ID = B.CUSTOMER_ID
;

-- Semi JOIN -> Inner JOIN
SELECT A.*
FROM CUSTOMER A
INNER JOIN ORDER_DEMAND B
      ON (A.CUSTOMER_ID = B.CUSTOMER_ID)
;

INSERT INTO ORDER_DEMAND VALUES ('1004', 'melon', '달콤비스킷');

-- Outer JOIN -> Outer JOIN
SELECT A.*, B.*
FROM CUSTOMER A, ORDER_DEMAND B
WHERE A.CUSTOMER_ID = B.CUSTOMER_ID(+)
;

SELECT A.*, B.*
FROM CUSTOMER A, ORDER_DEMAND B
WHERE A.CUSTOMER_ID(+) = B.CUSTOMER_ID
;

SELECT A.*, B.*
FROM CUSTOMER A
LEFT OUTER JOIN ORDER_DEMAND B
     ON A.CUSTOMER_ID = B.CUSTOMER_ID
;

SELECT A.*, B.*
FROM CUSTOMER A
RIGHT OUTER JOIN ORDER_DEMAND B
     ON A.CUSTOMER_ID = B.CUSTOMER_ID
;

SELECT A.*, B.*
FROM CUSTOMER A
FULL OUTER JOIN ORDER_DEMAND B
     ON A.CUSTOMER_ID = B.CUSTOMER_ID
;
