CREATE TABLE CUSTOMER ( 
    CUSTOMER_ID VARCHAR(20) NOT NULL, 
    CUSTOMER_NAME VARCHAR(20) NOT NULL, 
    AGE INT, 
    GRADE VARCHAR(10) NOT NULL, 
    JOB VARCHAR(20), 
    POINT INT DEFAULT 0, 
    PRIMARY KEY(CUSTOMER_ID) 
);

CREATE TABLE DELIVERY ( 
    DELIVERY_NO CHAR(3) NOT NULL, 
    DELIVERY_NAME VARCHAR(20), 
    ADDRESS VARCHAR(100), 
    TEL VARCHAR(20), 
    PRIMARY KEY(DELIVERY_NO) 
);

CREATE TABLE PRODUCT ( 
    PRODUCT_NO CHAR(3) NOT NULL, 
    PRODUCT_NAME VARCHAR(20), 
    STOCK INT, 
    BASE_PRICE INT, 
    MANUFACT VARCHAR(20), 
    PRIMARY KEY(PRODUCT_NO), 
    CHECK (STOCK >= 0 AND STOCK <= 10000) 
);

CREATE TABLE ORDER_DEMAND ( 
    ORDER_NO CHAR(3) NOT NULL, 
    CUSTOMER_ID VARCHAR(20), 
    PRODUCT_NO CHAR(3), 
    QTY INT, 
    ORDER_ADDR VARCHAR(30), 
    ORDER_DT DATE, 
    PRIMARY KEY(ORDER_NO), 
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),  
    FOREIGN KEY(PRODUCT_NO) REFERENCES PRODUCT(PRODUCT_NO) 
);